server:
  port: 8001

spring:
#  application:
#    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mycloud2020?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  type-aliases-package: com.atguigu.springcloud.entity #所有Entity别名类所在包
  mapperLocations: classpath:mapper/*.xml

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      #defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true  #访问路径可以显示IP地址